### ISSUE TITLE
URI.parse doesn't support IPv6 addresses

### ISSUE THREAD

**Issue by robertgrimm** [faye/faye#484]
The problem is that it assumes a ":" will only show up as the separator between the hostname and the port and that's not the case when a literal IPv6 address is used.  For example:
URI.parse("http://[2620:a3:e030:11a1:215:17ff:fee9:3068]:9292/").hostname -> "[2620".  This causes Faye to not work when an IPv6 address endpoint is used.

**Comment by jcoglan** [comment]
I've just fixed this in https://github.com/faye/faye/commit/dc754e38008cce762c9ea49fc713dadeeeaad63d. Can you try that out and confirm that it fixes your problem?

**Comment by robertgrimm** [comment]
You're close but IPv6 addresses need to be wrapped in square brackets.  For example, with your change: URI.stringify(URI.parse("http://[2620:a3:e030:11a1:215:17ff:fee9:3068]:9292/")) results in "http://2620:a3:e030:11a1:215:17ff:fee9:3068:9292/".  It needs to be "http://[2620:a3:e030:11a1:215:17ff:fee9:3068]:9292/".  I'll let you decide if you want to do that in parse when setting uri.hostname or somewhere else.

**Comment by robertgrimm** [comment]
https://github.com/faye/faye/commit/dc754e38008cce762c9ea49fc713dadeeeaad63d partially fixes the problem but it's still not quite right because it doesn't wrap IPv6 addresses in square brackets.  It's easy for us to modify it and apply the fix locally but I'm going to wait at least a weak or 2 to see if upstream fixes it correctly.

**Comment by jcoglan** [comment]
I just pushed another commit to `master` that should fix this.

**Comment by robertgrimm** [comment]
Thanks!  Works good.

**Comment by jcoglan** [comment]
Just letting you know that the fix for this issue has finally been released in version 1.3.0.
